name: Run Python Script

on:
  workflow_dispatch:

env:
  secret_key: ${{ secrets.SECRET_KEY }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Script
        run:
          pip install requests
          python update main.py 